version: '2'
services:
  server:
    environment:
      - PORT=3000
      - PGHOST=postgres
      - PGPORT=5432
      - NODE_ENV=production
    image: palaogn/tictactoe:${GIT_COMMIT}
    ports:
      - '3000:3000'
      - '8080:8080'
    depends_on:
      - postgres
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    ports:
      - 5432:5432
