version: '2'
services:
  server:
    environment:
      - PORT=3000
      - PGHOST=postgres
      - PGPORT=5432
    image: palaogn/tictactoe:${GIT_COMMIT}
    build:
      context: '.'
      dockerfile: 'Dockerfile'
    ports:
      - '80:3000'
      - '8080:8080'
    depends_on:
      - postgres
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    ports:
      - 5432:5432
